spring.application.name=home-tm
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate // valida que las tablas coincidan con tus Entities, pero no las crea ni modifica.
spring.jpa.show-sql=true

